services:

    minimal-markdown-ebook:

        container_name: minimal-markdown-ebook

        image: softwareshinobi/minimal-markdown-ebook

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80

        environment:

            VIRTUAL_HOST: lorem.ipsum.example

            LETSENCRYPT_HOST: lorem.ipsum.example
